
#topics-realsense
color_topic: "/camera/color/image_raw"
depth_topic: "/camera/aligned_depth_to_color/image_raw"
intrinsic_topic: "/camera/aligned_depth_to_color/camera_info"
checkpoint_path: "/home/ros_ws/weights/best.pt"
factor_depth: 1000
block_height: 15
log: True
